### ISSUE TITLE
Not getting optimal RMSE when running program

### ISSUE THREAD

**Issue by dkawashima** [minfawang/rbmGPU#2]
Hello,

I have been able to read in the Netflix data, and minimize the RMSE to some degree, but, when running on the full dataset with 120 factors and 40 iterations, I am not seeing the RMSE of .907 or .92, and instead am hovering closer to 0.95. In terms of selecting the number of factors, number of iterations, and contrastive divergence parameters for training the full dataset, do you have any advice further from what you posted in  the README?

Thank you!

**Comment by minfawang** [comment]
@dkawashima sorry for the late response. I couldn't recall what exact parameters I used in training as it passed for ~2 years. I think you can try changing number of factors ranging from 50 to 1000.
